### ISSUE TITLE
Foreign key misconfiguration

### ISSUE THREAD

**Issue by odddkidout** [casact/FASLR#61]
Had some error while initializing a new project in freshly created database. 
Error Log for reference

```
$ python -m faslr.main
2022-04-04 12:16:00,573 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-04-04 12:16:00,573 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("project")
2022-04-04 12:16:00,573 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-04-04 12:16:00,574 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("project")
2022-04-04 12:16:00,574 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-04-04 12:16:00,574 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("country")
2022-04-04 12:16:00,575 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-04-04 12:16:00,575 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("country")
2022-04-04 12:16:00,575 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-04-04 12:16:00,575 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("state")
2022-04-04 12:16:00,576 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-04-04 12:16:00,576 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("state")
2022-04-04 12:16:00,576 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-04-04 12:16:00,576 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("lob")
2022-04-04 12:16:00,576 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-04-04 12:16:00,576 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("lob")
2022-04-04 12:16:00,576 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-04-04 12:16:00,577 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("user")
2022-04-04 12:16:00,577 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-04-04 12:16:00,577 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("user")
2022-04-04 12:16:00,577 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-04-04 12:16:00,578 INFO sqlalchemy.engine.Engine
CREATE TABLE project (
        project_id INTEGER NOT NULL,
        country_id INTEGER,
        state_id INTEGER,
        lob_id INTEGER,
        user_id INTEGER,
        created_on DATETIME,
        PRIMARY KEY (project_id),
        FOREIGN KEY(country_id) REFERENCES country (country_id),
        FOREIGN KEY(state_id) REFERENCES state (state_id),
        FOREIGN KEY(lob_id) REFERENCES lob (lob_id),
        FOREIGN KEY(user_id) REFERENCES user (user_id)
)


2022-04-04 12:16:00,578 INFO sqlalchemy.engine.Engine [no key 0.00016s] ()
2022-04-04 12:16:00,583 INFO sqlalchemy.engine.Engine
CREATE TABLE country (
        country_id INTEGER NOT NULL,
        country_name VARCHAR,
        project_tree_uuid VARCHAR,
        PRIMARY KEY (country_id),
        FOREIGN KEY(project_tree_uuid) REFERENCES project (project_id)
)


2022-04-04 12:16:00,583 INFO sqlalchemy.engine.Engine [no key 0.00020s] ()
2022-04-04 12:16:00,588 INFO sqlalchemy.engine.Engine
CREATE TABLE state (
        state_id INTEGER NOT NULL,
        country_id INTEGER,
        state_name VARCHAR,
        project_tree_uuid VARCHAR,
        PRIMARY KEY (state_id),
        FOREIGN KEY(country_id) REFERENCES country (country_id),
        FOREIGN KEY(project_tree_uuid) REFERENCES project (project_id)
)


2022-04-04 12:16:00,588 INFO sqlalchemy.engine.Engine [no key 0.00019s] ()
2022-04-04 12:16:00,593 INFO sqlalchemy.engine.Engine
CREATE TABLE lob (
        lob_id INTEGER NOT NULL,
        country_id INTEGER,
        state_id INTEGER,
        project_tree_uuid VARCHAR,
        lob_type VARCHAR,
        PRIMARY KEY (lob_id),
        FOREIGN KEY(country_id) REFERENCES country (country_id),
        FOREIGN KEY(state_id) REFERENCES state (state_id),
        FOREIGN KEY(project_tree_uuid) REFERENCES project (project_id)
)


2022-04-04 12:16:00,593 INFO sqlalchemy.engine.Engine [no key 0.00019s] ()
2022-04-04 12:16:00,598 INFO sqlalchemy.engine.Engine
CREATE TABLE user (
        user_id INTEGER NOT NULL,
        PRIMARY KEY (user_id)
)


2022-04-04 12:16:00,598 INFO sqlalchemy.engine.Engine [no key 0.00015s] ()
2022-04-04 12:16:00,606 INFO sqlalchemy.engine.Engine COMMIT
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\relationships.py", line 2754, in _determine_joins
    self.primaryjoin = join_condition(
  File "<string>", line 2, in join_condition
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\sql\selectable.py", line 1217, in _join_condition
    cls._joincond_trim_constraints(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\sql\selectable.py", line 1338, in _joincond_trim_constraints
    raise exc.AmbiguousForeignKeysError(
sqlalchemy.exc.AmbiguousForeignKeysError: Can't determine join between 'project' and 'country'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\faslr2\FASLR\faslr\project.py", line 57, in <lambda>
    self.button_box.accepted.connect(lambda main_window=self.main_window: self.make_project(main_window))
  File "C:\Users\admin\Desktop\faslr2\FASLR\faslr\project.py", line 88, in make_project
    country_query = session.query(CountryTable).filter(CountryTable.country_name == country_text)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 2139, in query
    return self._query_cls(entities, self, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\query.py", line 180, in __init__
    self._set_entities(entities)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\query.py", line 187, in _set_entities
    self._raw_columns = [
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\query.py", line 188, in <listcomp>
    coercions.expect(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\sql\coercions.py", line 181, in expect
    insp._post_inspect
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1180, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\mapper.py", line 2123, in _post_inspect
    self._check_configure()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\mapper.py", line 1900, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\mapper.py", line 3418, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\mapper.py", line 3457, in _do_configure_registries
    mapper._post_configure_properties()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\mapper.py", line 1917, in _post_configure_properties
    prop.init()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\interfaces.py", line 231, in init
    self.do_init()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\relationships.py", line 2152, in do_init
    self._setup_join_conditions()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\relationships.py", line 2248, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\relationships.py", line 2643, in __init__
    self._determine_joins()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\relationships.py", line 2806, in _determine_joins
    util.raise_(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship ProjectTable.country - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.

```

**Comment by genedan** [comment]
This was a result of me experimenting with the relationships in the schema. The DB isn't really in a mature state right now so you should expect it to change quite drastically over the next few months. I'll probably have time to get it stabilized and add some unit tests over the weekend.
